export const experience = {
  en: {
    headline: ["The right message.", "At their moment."],
    intro:
      "Turn customer actions into thoughtful journeys. Open source. On your infrastructure.",
    explore: "Explore a journey",
    install: "Self-host NudgeOn",
    start: "Start building",
    source: "View on GitHub",
    product: "Product",
    journeys: "Journeys",
    guide: "User guide",
    developers: "Developers",
    interactive: "Interactive preview",
    note: "Sample journey · No messages are sent",
    preview: "Message preview",
    title: "Title",
    body: "Body",
    replay: "Replay preview",
    replaying: "Playing the journey…",
    complete: "Journey complete",
    result: "Preview complete. Your message is ready to explore.",
    now: "now",
    steps: ["Event", "Wait", "Message"],
    stepHint: "Choose a step to explore the flow.",
    featureTitle: "From a signal to a conversation.",
    featureIntro: "One connected workflow. Fewer disconnected tools.",
    features: [
      [
        "Know the moment",
        "Bring events and customer profiles together. Find the people who need to hear from you.",
      ],
      [
        "Build the next step",
        "Connect triggers, waits and messages into a journey you can see and refine.",
      ],
      [
        "See what happened",
        "Trace messages from send to delivery and open. Understand why a message was skipped.",
      ],
    ],
    sample: "Illustrative product examples",
    status: ["Opened", "Delivered", "Skipped"],
    logNames: ["Welcome", "Update", "Reminder"],
    moments: "Made for the moments that matter.",
    momentLinks: ["Onboarding", "Re-engagement", "Service updates"],
    deployTitle: ["Your customers.", "Your infrastructure."],
    deployIntro:
      "Start with the open-source edition. Keep your data and your messaging workflow under your control.",
    setup: "Open the setup guide",
    viewSource: "View source",
    terminal: "Install → connect → send your first push",
    beta: "Partner beta candidate",
    betaBody:
      "iOS and Android SDK 0.2.6 are published. React Native and Flutter release preparation is complete; public publication and wider beta validation are still pending.",
    checklist: "See the release checklist",
    finalTitle: "Make your next message matter.",
    finalCta: "Build your first journey",
    footer: "Open-source customer engagement.",
    contact: "Contact",
    scenarios: [
      {
        id: "welcome",
        name: "Welcome new users",
        description: "A thoughtful first hello, right when they join.",
        event: "sign_up",
        eventLabel: "Account created",
        wait: "Wait 10 minutes",
        message: "Send a welcome push",
        title: "A good place to start",
        body: "Your next favorite thing is waiting. Take a look around.",
        hints: [
          "Start when your app sends a sign_up event.",
          "Give new customers ten minutes to settle in.",
          "Edit the copy. See how it feels on their screen.",
        ],
      },
      {
        id: "return",
        name: "Bring them back",
        description: "Keep the conversation going after a meaningful visit.",
        event: "product_viewed",
        eventLabel: "Product viewed",
        wait: "Wait 1 day",
        message: "Send a reminder",
        title: "Still on your mind?",
        body: "Pick up where you left off. Your next discovery is just a tap away.",
        hints: [
          "Start with a product_viewed event from your app.",
          "Wait a day. Exit if purchase_completed arrives.",
          "A timely reminder, with room for your own voice.",
        ],
      },
      {
        id: "update",
        name: "Share an update",
        description: "Keep subscribers in the loop when something changes.",
        event: "playlist_updated",
        eventLabel: "Playlist updated",
        wait: null,
        message: "Notify subscribers",
        title: "Your playlist has an update",
        body: "Something changed in a playlist you follow. Tap to see what is new.",
        hints: [
          "Send playlist_updated for each subscribed customer.",
          "",
          "A transactional update that takes them back to your app.",
        ],
      },
    ],
  },
  ko: {
    headline: ["필요한 메시지가,", "필요한 순간에."],
    intro:
      "고객의 행동을 다음 대화로 연결하세요. 우리 인프라에서 시작하는 오픈소스 고객 인게이지먼트.",
    explore: "저니 직접 체험하기",
    install: "NudgeOn 직접 설치",
    start: "시작하기",
    source: "GitHub에서 살펴보기",
    product: "제품",
    journeys: "저니 체험",
    guide: "유저가이드",
    developers: "개발자센터",
    interactive: "직접 체험하는 저니",
    note: "예시 저니 · 실제 메시지는 발송되지 않습니다",
    preview: "메시지 미리보기",
    title: "제목",
    body: "본문",
    replay: "흐름 재생하기",
    replaying: "저니를 재생하고 있어요…",
    complete: "저니 완료",
    result: "미리보기 완료. 메시지를 바꾸고 다시 확인해 보세요.",
    now: "지금",
    steps: ["이벤트", "대기", "메시지"],
    stepHint: "단계를 눌러 흐름을 살펴보세요.",
    featureTitle: "하나의 행동에서, 다음 대화까지.",
    featureIntro: "흩어져 있던 고객 데이터와 메시지를 하나의 흐름으로.",
    features: [
      [
        "고객의 순간을 발견하고",
        "이벤트와 고객 프로필을 연결하세요. 지금 메시지가 필요한 고객을 찾을 수 있습니다.",
      ],
      [
        "다음 행동을 설계하고",
        "이벤트, 대기, 메시지를 연결하세요. 눈에 보이는 저니로 흐름을 만들고 다듬습니다.",
      ],
      [
        "그 이후까지 확인하세요",
        "발송부터 도달과 열기까지 따라가세요. 메시지를 보내지 못한 이유도 확인합니다.",
      ],
    ],
    sample: "제품 이해를 돕기 위한 예시 화면",
    status: ["열기", "도달", "건너뜀"],
    logNames: ["환영 메시지", "업데이트", "리마인더"],
    moments: "중요한 순간마다, 자연스럽게.",
    momentLinks: ["첫 만남", "다시 방문할 이유", "꼭 필요한 소식"],
    deployTitle: ["고객도, 데이터도.", "우리 팀의 방식으로."],
    deployIntro:
      "오픈소스 버전으로 시작하세요. 고객 데이터와 메시지 운영을 우리 인프라에서 직접 관리합니다.",
    setup: "설치 가이드 열기",
    viewSource: "소스 코드 보기",
    terminal: "설치 → 앱 연결 → 첫 푸시 발송",
    beta: "파트너 베타 후보",
    betaBody:
      "iOS·Android SDK 0.2.6가 공개돼 있습니다. React Native·Flutter는 배포 준비를 마쳤으며, 공개 게시와 더 넓은 베타 검증이 남아 있습니다.",
    checklist: "출시 체크리스트 보기",
    finalTitle: "다음 메시지를, 기다려지는 메시지로.",
    finalCta: "첫 저니 시작하기",
    footer: "오픈소스 고객 인게이지먼트 플랫폼.",
    contact: "문의하기",
    scenarios: [
      {
        id: "welcome",
        name: "반가운 첫 만남",
        description: "가입한 고객에게, 좋은 시작이 되는 첫인사를 건네세요.",
        event: "sign_up",
        eventLabel: "회원가입 완료",
        wait: "10분 기다리기",
        message: "환영 푸시 보내기",
        title: "잘 오셨어요, 여기서 시작해요",
        body: "취향에 꼭 맞는 새로운 발견이 기다리고 있어요. 지금 둘러보세요.",
        hints: [
          "앱에서 sign_up 이벤트가 들어오면 시작합니다.",
          "새로운 고객이 둘러볼 수 있도록 10분을 기다립니다.",
          "문구를 바꿔 보세요. 고객의 화면에 바로 반영됩니다.",
        ],
      },
      {
        id: "return",
        name: "다시 방문할 이유",
        description: "관심을 보인 고객에게, 이어갈 이야기를 전하세요.",
        event: "product_viewed",
        eventLabel: "상품 조회",
        wait: "하루 기다리기",
        message: "리마인더 보내기",
        title: "아직 마음에 남아 있나요?",
        body: "눈여겨본 상품을 다시 만나보세요. 지난번의 발견을 이어갈 수 있어요.",
        hints: [
          "앱의 product_viewed 이벤트에서 시작합니다.",
          "하루 기다리고, purchase_completed가 오면 종료합니다.",
          "우리 서비스의 목소리로, 부담 없는 한마디를 전하세요.",
        ],
      },
      {
        id: "update",
        name: "꼭 필요한 새 소식",
        description: "구독한 콘텐츠가 바뀌면, 기다리던 고객에게 알려주세요.",
        event: "playlist_updated",
        eventLabel: "콘티 업데이트",
        wait: null,
        message: "구독자에게 알리기",
        title: "구독한 콘티가 수정됐어요",
        body: "함께 보고 있는 콘티에 새 소식이 있어요. 바뀐 내용을 확인해 보세요.",
        hints: [
          "각 구독자의 ID로 playlist_updated 이벤트를 보냅니다.",
          "",
          "서비스 이용에 필요한 소식을 거래성 메시지로 보냅니다.",
        ],
      },
    ],
  },
};
